CREATE TABLE BITACORA(
	BITACORA_ID INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CONTRASENA_NUEVA varchar(8) NOT NULL,
    CONTRASENA_ANT varchar(8) NOT NULL,
    USUARIO_ID INT(8),
    FEC_CREACION DATE,
	USUARIO_CREACION VARCHAR(10),
	FEC_ULTIMA_MODIFICACION DATE,
	USUARIO_ULTIMA_MODIFICACION VARCHAR(10),
    FOREIGN KEY (USUARIO_ID) 
	REFERENCES USUARIO(USUARIO_ID)
);

DELIMITER $$
CREATE TRIGGER BEFORE_INSERT_BITACORA
  BEFORE INSERT ON BITACORA FOR EACH ROW
BEGIN
	SET NEW.USUARIO_CREACION:= current_user();
    SET NEW. FEC_CREACION:= curdate();
END$$

DELIMITER $$
CREATE TRIGGER BEFORE_UPDATE_BITACORA
  BEFORE UPDATE ON PROGRA_2.BITACORA FOR EACH ROW
BEGIN
	SET NEW.USUARIO_ULTIMA_MODIFICACION:= current_user();
	SET NEW.FEC_ULTIMA_MODIFICACION:= curdate();
END$$