/* Autor: Erin Siezar
*  Fecha: 31/05/2015 */

CREATE TABLE CORREO(
	CORREO_ID INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CORREO VARCHAR(30) unique,
    PERSONA_ID INT(8),
    FEC_CREACION DATE,
	USUARIO_CREACION VARCHAR(10),
	FEC_ULTIMA_MODIFICACION DATE,
	USUARIO_ULTIMA_MODIFICACION VARCHAR(10),
    FOREIGN KEY (PERSONA_ID) 
	REFERENCES PERSONA(PERSONA_ID)
);

DELIMITER $$
CREATE TRIGGER BEFORE_INSERT_CORREO
  BEFORE INSERT ON CORREO FOR EACH ROW
BEGIN
	SET NEW.USUARIO_CREACION:= current_user();
    SET NEW. FEC_CREACION:= curdate();
END$$

DELIMITER $$
CREATE TRIGGER BEFORE_UPDATE_CORREO
  BEFORE UPDATE ON PROGRA_2.CORREO FOR EACH ROW
BEGIN
	SET NEW.USUARIO_ULTIMA_MODIFICACION:= current_user();
	SET NEW.FEC_ULTIMA_MODIFICACION:= curdate();
END$$