CREATE TABLE ESPECIE (
    ESPECIE_ID INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30) UNIQUE,
    GENERO_ID INT(8),
    CANTIDAD_HUEVOS_ID INT(8),
    NOMBRE_INGLES_ID INT(8),
    NOMBRE_COMUN_ID INT(8),
    TAMAÑO_ID INT(8),
    ZONA_VIDA_ID INT(8),
    PICO_ID INT(8),
    FEC_CREACION DATE,
    USUARIO_CREACION VARCHAR(10),
    FEC_ULTIMA_MODIFICACION DATE,
    USUARIO_ULTIMA_MODIFICACION VARCHAR(10),
    FOREIGN KEY (GENERO_ID)
        REFERENCES GENERO (GENERO_ID),
    FOREIGN KEY (CANTIDAD_HUEVOS_ID)
        REFERENCES CANTIDAD_HUEVOS (CANTIDAD_HUEVOS_ID),
    FOREIGN KEY (NOMBRE_INGLES_ID)
        REFERENCES NOMBRE_INGLES (NOMBRE_INGLES_ID),
	FOREIGN KEY(NOMBRE_COMUN_ID)
		REFERENCES NOMBRE_COMUN(NOMBRE_COMUN_ID),
	FOREIGN KEY(TAMAÑO_ID)
		REFERENCES TAMAÑO(TAMAÑO_ID),
	FOREIGN KEY(ZONA_VIDA_ID)
		REFERENCES ZONA_VIDA(ZONA_VIDA_ID),
	FOREIGN KEY(PICO_ID)
		REFERENCES PICO(PICO_ID)
);

DELIMITER $$
CREATE TRIGGER BEFORE_INSERT_ESPECIE
  BEFORE INSERT ON ESPECIE FOR EACH ROW
BEGIN
	SET NEW.USUARIO_CREACION:= current_user();
    SET NEW. FEC_CREACION:= curdate();
END$$

DELIMITER $$
CREATE TRIGGER BEFORE_UPDATE_ESPECIE
  BEFORE UPDATE ON PROGRA_2.ESPECIE FOR EACH ROW
BEGIN
	SET NEW.USUARIO_ULTIMA_MODIFICACION:= current_user();
	SET NEW.FEC_ULTIMA_MODIFICACION:= curdate();
END$$