CREATE TABLE FOTO_AVE(
	FOTO_AVE_ID INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FOTO blob NOT NULL,
    ESTADO_ID INT(8),
    PERSONA_ID INT(8),
    ESPECIE_ID INT(8),
    FEC_CREACION DATE,
	USUARIO_CREACION VARCHAR(10),
	FEC_ULTIMA_MODIFICACION DATE,
	USUARIO_ULTIMA_MODIFICACION VARCHAR(10),
    FOREIGN KEY (ESTADO_ID) 
	REFERENCES ESTADO(ESTADO_ID),
    FOREIGN KEY (PERSONA_ID) 
	REFERENCES PERSONA(PERSONA_ID),
    FOREIGN KEY (ESPECIE_ID) 
	REFERENCES ESPECIE(ESPECIE_ID)
    
);

DELIMITER $$
CREATE TRIGGER BEFORE_INSERT_FOTO_AVE
  BEFORE INSERT ON FOTO_AVE FOR EACH ROW
BEGIN
	SET NEW.USUARIO_CREACION:= current_user();
    SET NEW. FEC_CREACION:= curdate();
END$$

DELIMITER $$
CREATE TRIGGER BEFORE_UPDATE_FOTO_AVE
  BEFORE UPDATE ON PROGRA_2.FOTO_AVE FOR EACH ROW
BEGIN
	SET NEW.USUARIO_ULTIMA_MODIFICACION:= current_user();
	SET NEW.FEC_ULTIMA_MODIFICACION:= curdate();
END$$