-- Autor: Javier Rivas
-- Fecha: 26/05/15
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Sayornis',3);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Muscivora',3);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Tyrannus',3);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Myiodynastes',3);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Megarhynchus',3);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Myiozetetes',3);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Pitangus',3);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Myiobius',3);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Onychorhynchus',3);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Tolmomyias',3);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Todirostrum',3);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Serpophaga',3);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Elaenia',3);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Mionectes',3);
