-- Autor: Javier Rivas
-- Fecha: 26/05/15
INSERT INTO PICO(PICO_ID,NOMBRE) VALUES (1,'Generalista');
INSERT INTO PICO(PICO_ID,NOMBRE) VALUES (2,'Insectívoro');
INSERT INTO PICO(PICO_ID,NOMBRE) VALUES (3,'Granívoro');
INSERT INTO PICO(PICO_ID,NOMBRE) VALUES (4,'Comedor de semillas');
INSERT INTO PICO(PICO_ID,NOMBRE) VALUES (5,'Nectarívoro');
INSERT INTO PICO(PICO_ID,NOMBRE) VALUES (6,'Frugívoro');
INSERT INTO PICO(PICO_ID,NOMBRE) VALUES (7,'Pájaro carpintero');
INSERT INTO PICO(PICO_ID,NOMBRE) VALUES (8,'Pico-bolsa');
INSERT INTO PICO(PICO_ID,NOMBRE) VALUES (9,'Limícola');
INSERT INTO PICO(PICO_ID,NOMBRE) VALUES (10,'Filtrador');
INSERT INTO PICO(PICO_ID,NOMBRE) VALUES (11,'Pescador');
INSERT INTO PICO(PICO_ID,NOMBRE) VALUES (12,'Buceador');
INSERT INTO PICO(PICO_ID,NOMBRE) VALUES (13,'Carroñero');
INSERT INTO PICO(PICO_ID,NOMBRE) VALUES (14,'Ave de presa');