-- Autor: Javier Rivas
-- Fecha: 26/05/15
INSERT INTO ZONA_VIDA(NOMBRE) VALUES ('Zona Tropical');
INSERT INTO ZONA_VIDA(NOMBRE) VALUES ('Zona Subtropical');
INSERT INTO ZONA_VIDA(NOMBRE) VALUES ('Zona Templada');
INSERT INTO ZONA_VIDA(NOMBRE) VALUES ('Zona del Páramo');