/*
Autor: Javier Rivas
Fecha: 04/06/14
*/
#Inserts de alimentos
INSERT INTO ALIMENTO(DESCRIPCION) VALUES("Insectos");
INSERT INTO ALIMENTO(DESCRIPCION) VALUES("Frutas rojas");
INSERT INTO ALIMENTO(DESCRIPCION) VALUES("Frutitas");
INSERT INTO ALIMENTO(DESCRIPCION) VALUES("Ranas pequeñas");
INSERT INTO ALIMENTO(DESCRIPCION) VALUES("Lagartijas");
INSERT INTO ALIMENTO(DESCRIPCION) VALUES("Renacuajos");
INSERT INTO ALIMENTO(DESCRIPCION) VALUES("Frutas");
INSERT INTO ALIMENTO(DESCRIPCION) VALUES("Peces pequeños");
INSERT INTO ALIMENTO(DESCRIPCION) VALUES("Semillas pequeñas");
