-- Autor: Javier Rivas
-- Fecha: 26/05/15
INSERT INTO NOMBRE_COMUN(NOMBRE) VALUES ('Mosquero de agua');
INSERT INTO NOMBRE_COMUN(NOMBRE) VALUES ('Mosquero tijereta');
INSERT INTO NOMBRE_COMUN(NOMBRE) VALUES ('Pájaro rey tropical');
INSERT INTO NOMBRE_COMUN(NOMBRE) VALUES ('Mosquero listado');
INSERT INTO NOMBRE_COMUN(NOMBRE) VALUES ('Mosquerón picudo');
INSERT INTO NOMBRE_COMUN(NOMBRE) VALUES ('Mosquero cejiblanco');
INSERT INTO NOMBRE_COMUN(NOMBRE) VALUES ('Bienteveo grande');
INSERT INTO NOMBRE_COMUN(NOMBRE) VALUES ('Mosquerito rabadilla azufrada');
INSERT INTO NOMBRE_COMUN(NOMBRE) VALUES ('Mosquero real norteño');
INSERT INTO NOMBRE_COMUN(NOMBRE) VALUES ('Piquiplano azufrado');
INSERT INTO NOMBRE_COMUN(NOMBRE) VALUES ('Espatulilla común');
INSERT INTO NOMBRE_COMUN(NOMBRE) VALUES ('Mosquerito guardarríos');
INSERT INTO NOMBRE_COMUN(NOMBRE) VALUES ('Elainia montañera');
INSERT INTO NOMBRE_COMUN(NOMBRE) VALUES ('Mosquerito aceitunado');