-- Autor: Javier Rivas
-- Fecha: 26/05/15
INSERT INTO PICO(NOMBRE) VALUES ('Granívoro');
INSERT INTO PICO(NOMBRE) VALUES ('Insectívoro');
INSERT INTO PICO(NOMBRE) VALUES ('Carnívoro');
INSERT INTO PICO(NOMBRE) VALUES ('Piscívoro');
INSERT INTO PICO(NOMBRE) VALUES ('Frugívoro');
INSERT INTO PICO(NOMBRE) VALUES ('Filtrador');
INSERT INTO PICO(NOMBRE) VALUES ('Limnícola');
INSERT INTO PICO(NOMBRE) VALUES ('Nectívoro');