-- Autor: Javier Rivas
-- Fecha: 26/05/15
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES,NOMBRE_COMUN,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Nigricans', 1,1,'Black Phoebe','Mosquero de agua',1,1,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES,NOMBRE_COMUN,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Tyrannus', 2,2,'Fork-tailed Flycatcher','Mosquero tijereta',2,2,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES,NOMBRE_COMUN,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Melancholicus', 3,1,'Tropical Kingbird','Pájaro rey tropical',3,2,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES,NOMBRE_COMUN,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Maculatus', 4,1,'Streaked Flycatcher','Mosquero listado',3,1,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES,NOMBRE_COMUN,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Pitangua', 5,1,'Boat-biller Flycatcher','Mosquero cejiblanco',4,2,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES,NOMBRE_COMUN,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Similis', 6,3,'Vermilion-crowned Flycatcher','Mosquero cejiblanco',1,2,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES,NOMBRE_COMUN,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Sulphuratus',7,2,'Great Kiskadee','Bienteveo grande',4,1,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES,NOMBRE_COMUN,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Sulphureipygius', 8,4,'Sulphur-rumped Flycatcher','Mosquerito rabadilla azufrada',5,1,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES,NOMBRE_COMUN,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Mexicanus', 9,4,'Northern Royal Flycatcher','Mosquero real norteño',1,1,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES,NOMBRE_COMUN,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Sulphurescens', 10,1,'Yellow-olive Flycatcher','Piquiplano azufrado',6,1,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES,NOMBRE_COMUN,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Cinereum', 11,1,'Black-fronted Tody-Flycatcher','Espatulilla común',7,2,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES,NOMBRE_COMUN,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Cinerea',12,4,'Torrent Flycatcher','Mosquerito guardarríos',8,1,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES,NOMBRE_COMUN,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Frantzii', 13,4,'Mountain Elaenia','Elainia montañera',9,3,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES,NOMBRE_COMUN,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Oleagineus', 14,1,'Oleaginous Pipromorpha','Mosquerito aceitunado',5,1,2);
