-- Autor: Javier Rivas
-- Fecha: 26/05/15
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Sayornis',2);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Muscivora',2);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Tyrannus',2);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Myiodynastes',2);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Megarhynchus',2);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Myiozetetes',2);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Pitangus',2);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Myiobius',2);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Onychorhynchus',2);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Tolmomyias',2);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Todirostrum',2);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Serpophaga',2);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Elaenia',2);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Mionectes',2);
