-- Autor: Javier Rivas
-- Fecha: 26/05/15
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Sayornis',1);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Muscivora',1);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Tyrannus',1);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Myiodynastes',1);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Megarhynchus',1);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Myiozetetes',1);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Pitangus',1);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Myiobius',1);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Onychorhynchus',1);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Tolmomyias',1);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Todirostrum',1);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Serpophaga',1);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Elaenia',1);
INSERT INTO GENERO(NOMBRE,FAMILIA_ID) VALUES ('Mionectes',1);
