-- Autor: Javier Rivas
-- Fecha: 26/05/15
INSERT INTO TAMAÑO(TAMAÑO) VALUES ('16 cm');
INSERT INTO TAMAÑO(TAMAÑO) VALUES ('24-36 cm');
INSERT INTO TAMAÑO(TAMAÑO) VALUES ('20 cm');
INSERT INTO TAMAÑO(TAMAÑO) VALUES ('22 cm');
INSERT INTO TAMAÑO(TAMAÑO) VALUES ('12 cm');
INSERT INTO TAMAÑO(TAMAÑO) VALUES ('12,5 cm');
INSERT INTO TAMAÑO(TAMAÑO) VALUES ('9,5 cm');
INSERT INTO TAMAÑO(TAMAÑO) VALUES ('10 cm');
INSERT INTO TAMAÑO(TAMAÑO) VALUES ('15 cm');