/*
Autor: Javier Rivas
Fecha: 04/06/14
*/
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (1,1);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (1,2);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (2,2);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (1,3);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (3,3);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (4,3);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (1,4);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (5,4);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (1,5);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (7,5);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (1,6);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (3,6);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (6,6);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (1,7);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (7,7);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (8,7);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (1,8);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (1,9);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (1,10);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (3,10);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (1,11);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (1,12);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (1,13);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (3,13);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (1,14);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (7,14);
INSERT INTO ALIMENTO_X_ESPECIE(ALIMENTO_ID,ESPECIE_ID) VALUES (9,14);