-- Autor: Javier Rivas
-- Fecha: 26/05/15
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES_ID,NOMBRE_COMUN_ID,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Nigricans', 3,1,1,1,1,1,1);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES_ID,NOMBRE_COMUN_ID,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Tyrannus', 4,2,2,2,2,2,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES_ID,NOMBRE_COMUN_ID,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Melancholicus', 5,1,3,3,3,2,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES_ID,NOMBRE_COMUN_ID,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Maculatus', 6,1,4,4,3,1,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES_ID,NOMBRE_COMUN_ID,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Pitangua', 7,1,5,5,4,2,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES_ID,NOMBRE_COMUN_ID,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Similis', 8,3,6,6,1,2,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES_ID,NOMBRE_COMUN_ID,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Sulphuratus',9,2,7,7,4,1,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES_ID,NOMBRE_COMUN_ID,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Sulphureipygius', 10,4,8,8,5,1,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES_ID,NOMBRE_COMUN_ID,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Mexicanus', 11,4,9,9,1,1,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES_ID,NOMBRE_COMUN_ID,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Sulphurescens', 12,1,10,10,6,1,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES_ID,NOMBRE_COMUN_ID,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Cinereum', 13,1,11,11,7,2,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES_ID,NOMBRE_COMUN_ID,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Cinerea',14,4,12,12,8,1,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES_ID,NOMBRE_COMUN_ID,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Frantzii', 15,4,13,13,9,3,2);
INSERT INTO ESPECIE(NOMBRE,GENERO_ID,CANTIDAD_HUEVOS_ID,NOMBRE_INGLES_ID,NOMBRE_COMUN_ID,TAMAÑO_ID,ZONA_VIDA_ID,PICO_ID)
VALUES ('Oleagineus', 16,1,14,14,5,1,2);