/* Autor: Erin Siezar
*  Fecha: 26/05/2015 */

CREATE TABLE TIPO_USUARIO(
	TIPO_USU_ID INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(30) unique,
    FEC_CREACION DATE,
	USUARIO_CREACION VARCHAR(10),
	FEC_ULTIMA_MODIFICACION DATE,
	USUARIO_ULTIMA_MODIFICACION VARCHAR(10)
);

DELIMITER $$
CREATE TRIGGER BEFORE_INSERT_TIPO_USU
  BEFORE INSERT ON tipo_usuario FOR EACH ROW
BEGIN
	SET NEW.USUARIO_CREACION:= current_user();
    SET NEW. FEC_CREACION:= curdate();
END$$

DELIMITER $$
CREATE TRIGGER BEFORE_UPDATE_TIPO_USU
  BEFORE UPDATE ON PROGRA_2.tipo_usuario FOR EACH ROW
BEGIN
	SET NEW.USUARIO_ULTIMA_MODIFICACION:= current_user();
	SET NEW.FEC_ULTIMA_MODIFICACION:= curdate();
END$$